chore: Fix earthengine-api version to 0.1.345
Prevents incompatibility errors arising from the breaking changes
introduced in version 1.x in Sept. 2024.

Error stack when running with earthengine 1.x

2024-09-15 11:52:17,028 : ERROR : delineator.heet_params : Problem updating Reservoir vector with calculated parameters
Traceback (most recent call last):
  File "/home/lepton/Documents/git_projects/geocaret/delineator/heet_params.py", line 2541, in batch_profile_reservoirs
    updated_reservoir_ftc = profile_reservoir(
  File "/home/lepton/Documents/git_projects/geocaret/delineator/heet_params.py", line 2384, in profile_reservoir
    landcover_bysoil_fracs = landcover_bysoil(
  File "/home/lepton/Documents/git_projects/geocaret/delineator/heet_params.py", line 875, in landcover_bysoil
    codes = ee.List(ee.List(frequency).map(generate_codes)).flatten()
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/ee_list.py", line 443, in map
    return apifunction.ApiFunction.call_(
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/apifunction.py", line 84, in call_
    return cls.lookup(name).call(*args, **kwargs)
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/function.py", line 62, in call
    return self.apply(self.nameArgs(args, kwargs))
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/function.py", line 75, in apply
    result = computedobject.ComputedObject(self, self.promoteArgs(named_args))
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/function.py", line 103, in promoteArgs
    promoted_args[name] = Function._promoter(args[name], arg_spec['type'])
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/__init__.py", line 336, in _Promote
    return CustomFunction.create(arg, 'Object', ['Object'] * args_count)
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/customfunction.py", line 126, in create
    return CustomFunction(signature, func)
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/customfunction.py", line 40, in __init__
    if body(*variables) is None:
  File "/home/lepton/Documents/git_projects/geocaret/delineator/heet_params.py", line 859, in generate_codes
    group_no = ee.Number.int(ee.Dictionary(d).get("group"))
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/ee_number.py", line 435, in int
    return apifunction.ApiFunction.call_(self.name() + '.int', self)
  File "/home/lepton/.pyenv/versions/heet38/lib/python3.8/site-packages/ee/apifunction.py", line 84, in call_
    return cls.lookup(name).call(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'call'